github: v8v88v8v88
patreon: v8v8v8v88
open_collective:
ko_fi: v8v88v8v88
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: v8v88v8v88
thanks_dev:
custom: https://www.paypal.me/v8pay
